apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base manifests を参照
resources:
  - ../../manifests

# Service の patch を適用
patchesStrategicMerge:
  - patch-grafana-svc.yaml
  - patch-prometheus-svc.yaml

# namespace を overlay で統一
namespace: monitoring

# オプション: ArgoCD で prune/replace されてもリソースが消えないように
commonLabels:
  app.kubernetes.io/managed-by: kustomize
