apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base manifests を参照
resources:
  - ../../manifests

# Service の patch を適用
patchesStrategicMerge:
  - patch-grafana-svc.yaml
  - patch-prometheus-svc.yaml
